### ISSUE TITLE
add CONTRIBUTING.md or similiar

### ISSUE THREAD

**Issue by tehofu** [telekom-security/telekom-security.github.io#23]
It should be easy for our colleagues to add new articles, so we should explain how to contribute to the site. Another motivation is that I've forgotten how to do it (I thought via creating a new branch and a pull request, but I can't create a new branch anymore!?)

**Comment by ziehmon** [comment]
Hi @tehofu,

first things first: we had to entirely wipe all repository permissions since there were external contributors/unknown accounts authorized as admins. The usual approach with GitHub is to fork the repository into your own namespace (so, `tehofu/telekom-security.github.io`) and then create a pull request from there into `telekom-security/telekom-security.github.io`).

Regarding your permissions: since you are a very frequent contributor (which we're very thankful for), I gave you **full admin** permissions. So, you'll be able to merge other people's PRs too. Happy to share the responsibility!

Regarding `CONTRIBUTING.md`, you're absolutely right and we should definitely do this. Would you be interested in writing such a small guide maybe? If not, I could take care of that, but not before next year.

Thanks for the heads up!
Simon :)

**Comment by t3chn0m4g3** [comment]
@tehofu Do you want to this?
